# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='days',
        ),
        migrations.AddField(
            model_name='week',
            name='pickled_days',
            field=models.CharField(default='[]', max_length=1024),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
