# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyassignment',
            name='period',
            field=models.IntegerField(choices=[(1, 'Period 1'), (2, 'Period 2'), (3, 'Period 3'), (4, 'Period 4'), (5, 'Activity 1'), (6, 'Activity 2')]),
        ),
    ]
