# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(help_text='3 letter code to identify classroom in schedule - e.g. 101, CAF', max_length=3),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(help_text='e.g. Classroom 101, Cafeteria', max_length=50),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(help_text='e.g. Period 3, Activity 2', max_length=12),
        ),
        migrations.AlterField(
            model_name='period',
            name='number',
            field=models.IntegerField(help_text='Determines the ordering of periods in a day. For example, if Period 4 is given number 4, and Activity 1 is given number 5, then Period 4 occurs right before Activity 1'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(help_text='e.g. Francisco, Western Addition', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesku',
            name='site',
            field=models.ForeignKey(help_text='Which site these units are being assigned to', on_delete=django.db.models.deletion.CASCADE, to='checkout.Site'),
        ),
        migrations.AlterField(
            model_name='sitesku',
            name='storage_location',
            field=models.CharField(blank=True, help_text="e.g. Closet in site directors's office", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitesku',
            name='units',
            field=models.IntegerField(help_text='Number of units being assigned to this site'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='display_name',
            field=models.CharField(help_text='Short name to show in schedule - e.g. MacbookPro13-2017', max_length=50),
        ),
        migrations.AlterField(
            model_name='sku',
            name='model_identifier',
            field=models.CharField(help_text='e.g. Apple 13.3" MacBook Pro (Mid 2017, Space Gray)', max_length=200),
        ),
        migrations.AlterField(
            model_name='sku',
            name='units',
            field=models.IntegerField(help_text='How many total functional units Aim High has available'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(help_text='Short name to display in schedule - e.g. KyraG', max_length=50),
        ),
        migrations.AlterField(
            model_name='week',
            name='days',
            field=models.ManyToManyField(blank=True, help_text='Working days in this week', to='checkout.Day'),
        ),
    ]
