# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20171002_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='collaborative',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
