# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20170825_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsagePurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(help_text='e.g. Research (Google, Wikipedia, Wolfram Alpha etc.)', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.UsagePurpose'),
        ),
    ]
