# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_reservation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
